### ISSUE TITLE
Right click in editor does not move the caret to position clicked

### ISSUE THREAD

**Issue by elextr** [techee/geany-lsp#22]
Geany 2.0 does, Scite does, Vscode does.

As a result the right click menu applies to the wrong thing.

**Comment by techee** [comment]
> Geany 2.0 does

Does it? It doesn't seem so.

That said, yes, I should use the position of the click and not the position of the caret.

**Comment by elextr** [comment]
Actually both do, right click on something it can't "goto symbol definition" on, like `while` and the caret moves there.   Probably be good if the caret move happened first, since the LSP needs the location.

**Comment by techee** [comment]
Ah, alright, you mean "after clicking goto" and not "right click alone" because the latter doesn't move anything.

**Comment by elextr** [comment]
Hmmmm, none of the right click menu actions seem to care about the click position, they all seem to only care about caret, thats really nasty, right click and move lines up, and the line with the caret moves, not the line clicked on.

Think thats a Geany one, will raise there.

**Comment by elextr** [comment]
> Ah, alright, you mean "after clicking goto" and not "right click alone" because the latter doesn't move anything.

Yes, Geany 2.0 uses the correct symbol (the one clicked on) but geany-lsp doesn't.

**Comment by techee** [comment]
OK, now thinking about it, it would really have to be Geany to move the caret when right-clicking - when the menu entry is clicked, it has no way of learning where the click event happened and there's nothing it could do.

But it's actually a bit questionable whether Geany should do that - the current state meets my expectations that the menu is relative to the caret position and not the click event position.

Anyway, closing here, not the plugin problem.

**Comment by techee** [comment]
> Yes, Geany 2.0 uses the correct symbol (the one clicked on) but geany-lsp doesn't.

Ah, really, reopening then. I have to check what Geany does exactly.

**Comment by techee** [comment]
It should be fixed now. I had to modify the Geany LSP interface to provide the position for goto definition/declaration. For other features invoked from the context menu I used the "update-editor-menu" signal to get the position.

**Comment by elextr** [comment]
Seems fixed.
