### ISSUE TITLE
Why can't TM symbol tree be used?

### ISSUE THREAD

**Issue by elextr** [techee/geany-lsp#35]
The first thing in README is to disable TM symbols for languages using LSPs.  But IIUC from discussions on https://github.com/geany/geany/pull/3849 the LSP symbol list is no longer used, and certainly leaving TM on works for me with C++ (which is all I tried so far)

**Comment by techee** [comment]
It does work, I'm just not happy with what I'd introduce to Geany with this patch: https://github.com/geany/geany/pull/3850/commits/98b7000e9c30be4bf2a255e99ad2460c80495ae3

One just has to check all the time whether the TMTag is Geany's TMTag or LSP's TMTag and the result is ugly and I don't know how to do in a non-ugly way.

I'll rather implement a separate symbol tree (and a separate sidebar tab) serving for LSP only.

**Comment by elextr** [comment]
> I'll rather implement a separate symbol tree (and a separate sidebar tab) serving for LSP only.

I don't see any problem with that, in fact I thought LSP could no longer be added to the TM symbols pane specifically because the mixed implementation was so messy.

**Comment by techee** [comment]
> I don't see any problem with that, in fact I thought LSP could no longer be added to the TM symbols pane specifically because the mixed implementation was so messy.

Well, the separate symbol tree isn't implemented yet - the one you were using before was the Geany's one. I'll try to start working on it soon - should pretty much be copy/paste.

**Comment by techee** [comment]
To clarify, having a separate symbol tree tab for LSP is possible but not very comfortable when switching among files of multiple languages where some are using LSP and the other use Geany's tag manager symbols - this then means the user has to switch between two symbol tree tabs.

Closing this issue in favor of #39.
