### ISSUE TITLE
TMIcon

### ISSUE THREAD

**Issue by ghost** [techee/geany-lsp#42]
When I try installing the plugin using ./autogen and make it shows an error which says 
`Unknown Type: TMIcon; did you mean GIcon`
and when I change it to GIcon it just says that its the wrong used of GIcon

**Comment by techee** [comment]
It's because you didn't compile and install the latest Geany from git master - LSP support isn't in the previous release.

**Comment by techee** [comment]
Closing as I believe the previous answer is correct. Feel free to reopen.
