### ISSUE TITLE
Investigate how to cancel multiple carets on move

### ISSUE THREAD

**Issue by techee** [techee/geany-lsp#49]
For Latex
```
\begin{$1}

\end{$1}
```
multiple carets can be added at the `$1` positions to edit the two values simultaneously. However, when moving up/down using keyboard arrows, all the carets move up/down. It would make more sense to disable multiple carets when keyboard arrow event happens but I'm not sure how to do it with Scintilla.

**Comment by techee** [comment]
What happens is this:
1. User selects autocompletion item

<img width="398" alt="Screenshot 2024-09-11 at 0 52 52" src="https://github.com/user-attachments/assets/fc70e5ad-0688-491d-bb27-f82d5db81222">

2. `\begin{} \end{}` is inserted and two carets are placed inside `{}` so editing happens simultaneously

<img width="398" alt="Screenshot 2024-09-11 at 0 53 39" src="https://github.com/user-attachments/assets/42e1d121-6b9b-4346-b2bb-5e07091f37f4">

3. User is done with editing inside `{}` so he presses arrow down to start editing the text in the block - what happens is this

<img width="398" alt="Screenshot 2024-09-11 at 0 54 01" src="https://github.com/user-attachments/assets/8eceaea7-384a-4737-a338-22f51e3b7946">

where both carets still exist. What I'd like to do is to keep only the primary caret. How can I detect arrow key presses to cancel multiple carets?

There is `SCN_UPDATEUI` with `SC_UPDATE_SELECTION` that probably gets fired but I guess it also gets fired when the caret moves as a result of inserting text so it won't detect arrow presses only.

@nyamatongwe Any idea?

**Comment by techee** [comment]
Alright, I think I could just intercept GTK keypress events and do `SCI_CANCEL` when arrows are pressed if there's not a better way.

**Comment by techee** [comment]
> Alright, I think I could just intercept GTK keypress events and do SCI_CANCEL when arrows are pressed if there's not a better way.

Done this way.

**Comment by nyamatongwe** [comment]
`SCN_UPDATEUI` is less specific than key monitoring but there are many keys bound to actions which may need to cancel.
