### ISSUE TITLE
HTML and CSS support

### ISSUE THREAD

**Issue by Johnmcenroyy** [techee/geany-lsp#53]
Hi @techee 
Please add support of HTML and CSS LSP servers.
I have added to lsp.conf:
```
[CSS]
cmd=vscode-css-languageserver --stdio

[HTML]
cmd=vscode-html-languageserver --stdio
```
but it didn't work.

Regards

**Comment by techee** [comment]
How did you install `vscode-css-languageserver` and `vscode-html-languageserver` - are these on your PATH? What happens when you run the commands from `cmd` from the command-line? If they are on PATH, these commands should just block until you press Ctrl+C.

**Comment by techee** [comment]
Also, do you see something when you run Tools->LSP Client->Server Initialize Responses? What are the messages shown in Geany's Status panel?

**Comment by techee** [comment]
You might also want to add
```ini
extra_identifier_characters=-
```
because `-` is used in CSS identifiers.

**Comment by techee** [comment]
And one more thing - did you enable LSP in the project settings for the project where you have HTML and CSS? Or are they by any chance outside the project directory? You can control this stuff by
```ini
use_without_project=
use_outside_project_dir=
project_root_marker_patterns=
```
Check the config file for more details about these.

**Comment by Johnmcenroyy** [comment]
@techee Thanks for info. Now it works, I have added:
```
use_outside_project_dir=true
use_without_project=true
```

**Comment by techee** [comment]
By the way, where did you get these language servers from? I'd like to test them too.

**Comment by Johnmcenroyy** [comment]
@techee 
vscode-css-languageserver and vscode-html-languageserver are in official repo of Arch Linux
https://archlinux.org/packages/extra/any/vscode-css-languageserver/
https://archlinux.org/packages/extra/any/vscode-html-languageserver/
https://wiki.archlinux.org/title/Language_Server_Protocol

I am shure you know about this page but if not, there is a good list of lsp:
https://langserver.org/

**Comment by techee** [comment]
> vscode-css-languageserver and vscode-html-languageserver are in official repo of Arch Linux

I use debian but I could try

https://github.com/hrsh7th/vscode-langservers-extracted

> I am shure you know about this page but if not, there is a good list of lsp:

Yeah, that's where I submitted Geany LSP client link ;-)

**Comment by Johnmcenroyy** [comment]
@techee Maybe you can extract binary packages from Arch Linux packages also. 
I have used some .deb packages so in Arch, also in Arch there is debtap script to convert .deb to Arch packages but
rarely use it, only for some very specific software such as Kubios etc.

Ah, yeah, now I see Geany LSP there :)
