### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by Johnmcenroyy** [techee/geany-lsp#55]
Please add support for https://github.com/artempyanykh/marksman markdown lsp server. It can be installed through
snap or pre-built binaries, there is in repo of Arch Linux, but seems there is no in Debian. I have added manually to config file, but don't understand it works or not, it initilized successfully and I see logs in terminal with ```rpc_log=stdout``` but nothing happens in editor. There is interesting article about marksman: https://medium.com/@chrisatmachine/lunarvim-improve-markdown-editing-with-marksman-739d06c73a26. Regards.

**Comment by techee** [comment]
I just fixed a problem with goto definition that didn't work but apart from that, everything else works for me. I used
```ini
[Markdown]
cmd=marksman server
use_outside_project_dir=true
use_without_project=true
#rpc_log=stdout
#rpc_log_full=true
#show_server_stderr=true
```

**Comment by Johnmcenroyy** [comment]
It seems it was my mistake, yes, it works. Thanks for checking.
