### ISSUE TITLE
rust-analyzer failing unexpectedly

### ISSUE THREAD

**Issue by computermouth** [techee/geany-lsp#61]
![2024-12-12--1734022980_604x131_scrot](https://github.com/user-attachments/assets/5112ddaa-e0c5-49d6-be8b-64ac56fab10a)

I use rust-analyzer at work. I set the global setting for `use_without_project`. I also enabled every setting I could find in terms of logging, and this is really all that comes out of it.

Just to see if the problem was actually with rust-analyzer, I also tried `gopls` with the same options, and that worked fine.

**Comment by techee** [comment]
> I use rust-analyzer at work. I set the global setting for use_without_project. 

Rust needs the information where the root of the project is. This can be achieved in two ways:
1. By creating a Geany project and setting it's base path to the root of the project
2. If you use`use_without_project`, you must tell the plugin how to detect root directory of projects implicitly. This is what `project_root_marker_patterns` is good for - when you set it for instance to `.git` the plugin will go up in the directory structure from the opened file and if some directory contains `.git`, it will be considered to be the root of the project.

Only languages like Python work without specifying root of the project under the condition that the python script is just a single file containing all the code.

> I also enabled every setting I could find in terms of logging, and this is really all that comes out of it.

By the way, the extra logs are shown in the terminal when you launch Geany from it, not in the messages window (when you enable full logging, the result is just too verbose to be displayed in the message window).

**Comment by computermouth** [comment]
I've tried `Cargo.toml` `Cargo.lock` and `.git`, which are all at the directory root, and saw no change.

> the extra logs are shown in the terminal when you launch Geany from it

Got it, the error message is [full output here](https://pastebin.com/raw/AwLsiLi7):

```
error: Unknown binary 'rust-analyzer' in official toolchain 'stable-x86_64-unknown-linux-gnu'.
```

**Comment by techee** [comment]
No idea what this particular message means but:
1. Would you try to use full path in the `cmd=` configuration
2. And before that, try to run this command from the terminal. If rust-analyzer works, it should just block when you start it (you can then terminate it with Ctrl+C)

**Comment by techee** [comment]
Sounds like this

https://github.com/rust-lang/rustup/issues/3846

If you really have 2 rust-analyzer versions installed like in this issue, absolute path to the correct version should solve it.

**Comment by computermouth** [comment]
> https://github.com/rust-lang/rustup/issues/3846

Yeah that was it, weird. I got the same error just running it from my terminal, but after deleting, and reinstalling via rustup, it worked fine.

Sorry to bombard you with user-error issues today. Thanks so much for building this plugin, is there anywhere I can donate to or sponsor your work?

**Comment by techee** [comment]
Good to hear. If you run into any other problems, just let me know.
