### ISSUE TITLE
Donation or Sponsorship

### ISSUE THREAD

**Issue by computermouth** [techee/geany-lsp#63]
This plugin is great. I love geany, and I think this plugin is important to geany remaining relevant in the future.

Where can I contribute financially to this plugin? (Github Sponsors, kofi, patreon, etc)

**Comment by techee** [comment]
Thanks, it's nice of you, but I don't really need any donation. If you feel like giving some money, you can donate to the Geany project:

https://www.geany.org/about/donate/

**Comment by computermouth** [comment]
![2024-12-12--1734037775_534x483_scrot](https://github.com/user-attachments/assets/23b3876b-1202-4d14-9ca0-a72c73ba26ea)

Thanks for all your work on this <3
